services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://root:teste123@mysql-db:3306/mydb"
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate dev &&
             npx prisma generate &&
             npm start"

volumes:
  db-data:
